version: "3.9"
services:
  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongo
    env_file: .env

  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: