name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: heroku container:login

    - name: Build and push Docker image
      run: |
        docker build -t github-monitor-integration .
        docker tag github-monitor-integration registry.heroku.com/github-monitor-integration/web
        docker push registry.heroku.com/github-monitor-integration/web

    - name: Release Docker image on Heroku
      run: heroku container:release web --app github-monitor-integration
